name: mambaenv
channels: 
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - pandas=1.5.3
  - python
  - wandb
  - pip
  - omegaconf
  - geopandas
  - jupyterlab
  - kornia 
  - lightning
  - matplotlib
  - osmnx
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - scikit-image
  - seaborn
  - timm
  - pytorch::torchvision
  - pip:
      - pip install -U 'jsonargparse[signatures]>=4.26.1
