name: dinov2-extras
channels:
  - defaults
  - pytorch
  - xformers
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision
  - omegaconf
  - torchmetrics
  - fvcore
  - iopath
  - xformers::xformers=0.0.18
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11
    - mmcv-full==1.5.0
    - mmsegmentation==0.27.0
